### ISSUE TITLE
[trajectory processing] glitches in time parameterisation

### ISSUE THREAD

**Issue by bit-pirate** [moveit/moveit_core#100]
Quite often motion plans executed on my robot look like getting stuck at some points in time. The robot slows down so much, that it looks like it has aborted the execution.

Looking further into this, I got the impression that the time parameterisation is not working correctly.

Here is one example trajectory output from move_group:

```
Waypoint 0
  Name                 : waypoint_0
  Angles               : [   0.81  -0.00   0.21  -1.49   1.22 ]
  Nominal Rates        : [   0.01   0.02   0.11   0.08   0.06 ]

Waypoint 1
  Name                 : waypoint_1
  Angles               : [   0.82   0.02   0.31  -1.42   1.27 ]
  Nominal Rates        : [   0.01   0.02   0.11   0.08   0.06 ]

Waypoint 2
  Name                 : waypoint_2
  Angles               : [   0.83   0.03   0.41  -1.34   1.32 ]
  Nominal Rates        : [   0.01   0.02   0.11   0.08   0.06 ]

Waypoint 3
  Name                 : waypoint_3
  Angles               : [   0.84   0.05   0.51  -1.27   1.37 ]
  Nominal Rates        : [   0.11   0.02   0.14   0.07   0.01 ]

Waypoint 4
  Name                 : waypoint_4
  Angles               : [   0.84   0.07   0.61  -1.20   1.42 ]
  Nominal Rates        : [   0.24   0.02   0.16   0.05   0.08 ]

Waypoint 5
  Name                 : waypoint_5
  Angles               : [   0.79   0.08   0.65  -1.18   1.40 ]
  Nominal Rates        : [   0.24   0.02   0.16   0.05   0.08 ]
```

While for most way points the nominal rates fit the positions, there are some entries, which look odd to me.

For example way point 3: I don't think the nominal rates are correct for entry (joint) 1 and 5.

With the subsequent interpolator adjusting the trajectory to fit this input, the result is the extreme slowing down of the motion explained above.

Any idea what could cause this?

**Comment by mikeferguson** [comment]
https://github.com/ros-planning/moveit/issues/160
