### ISSUE TITLE
Use of special characters in RobotModelLoader

### ISSUE THREAD

**Issue by dkotfis** [moveit/moveit_core#101]
Robot Model Loader currently throws an Invalid Name Exception loading joint limits for URDF/SRDF models with link or joint names using characters other than a-z, A-Z, 0-9, and _. The iRobot Hand URDF has joints using '[' and ']' characters, so it would be great if the loader supported them since other functions like Gazebo support them.

**Comment by isucan** [comment]
This is actually a limitation of the character set supported by the yaml format, so we cannot really fix this easily in moveit.
