### ISSUE TITLE
Add Python interface for RobotState class

### ISSUE THREAD

**Issue by liborw** [moveit/moveit_core#104]

**Comment by acornacorn** [comment]
How would this be used?

**Comment by isucan** [comment]
We need this in the Python bindings to better operate with states. This can help with FK, IK, attached objects.

**Comment by dyouakim** [comment]
Hi, I would like to know how to use this to get robot state and be able to update it after executing a plan (as a feed-back from the controller). or if there is any other way to set joint values, I would appreciate it. Thanks !

**Comment by mikeferguson** [comment]
Appears that at least a basic interface exists -- https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/planning_interface/robot_interface/src/wrap_python_robot_interface.cpp -- individual improvements should be ticketed in the new moveit repo
