### ISSUE TITLE
Test Broken: distance_field TestSignedPropagationDistanceField.TestOcTree

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#107]
/home/schitta/code/moveit/src/moveit_core/distance_field/test/test_distance_field.cpp:791: Failure
Value of: checkOctomapVersusDistanceField(df, tree)
  Actual: false
Expected: true
No point at potential boundary query 0 0.54 0
/home/schitta/code/moveit/src/moveit_core/distance_field/test/test_distance_field.cpp:803: Failure
Value of: checkOctomapVersusDistanceField(df, tree)
  Actual: false
Expected: true
No point at potential boundary query 2.24 0.96 0.96
/home/schitta/code/moveit/src/moveit_core/distance_field/test/test_distance_field.cpp:811: Failure
Value of: checkOctomapVersusDistanceField(df_oct, tree)
  Actual: false
Expected: true
Leaf node 0.525 0.525 0.525
Leaf node 0.675 0.525 0.525
Leaf node 1.025 0.525 0.525
Occupied cells 648
[  FAILED  ] TestSignedPropagationDistanceField.TestOcTree (5904 ms)

**Comment by acornacorn** [comment]
fixed
