### ISSUE TITLE
Test Broken: FclCollisionDetectionTester.ContactReporting

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#109]
/home/schitta/code/moveit/src/moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp:217: Failure
Value of: 2
Expected: res.contacts.size()
Which is: 1
[  FAILED  ] FclCollisionDetectionTester.ContactReporting (779 ms)

**Comment by mikeferguson** [comment]
fix merged
