### ISSUE TITLE
weight limit computation in kinematic_metrics

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_core#11]
The weight limit appears to be computed incorrectly. A value that looks a lot like uninitialized values or division by 0 appears on screen instead.

**Comment by sachinchitta** [comment]
Can you tell what I need to do to reproduce this error - preferably on Fuerte right now.

**Comment by jonbinney** [comment]
A wise man once told me that we should all be on groovy now.....

**Comment by sachinchitta** [comment]
Ok, fine! Tell me how to do it in Groovy. That was the best ticket response yet though :)

**Comment by sachinchitta** [comment]
Fixed in groovy-devel.
