### ISSUE TITLE
Test Broken: fcl FclCollisionDetectionTester.ContactPositions

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#110]
/home/schitta/code/moveit/src/moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp:257: Failure
Value of: res.collision
  Actual: false
Expected: true
[  FAILED  ] FclCollisionDetectionTester.ContactPositions (753 ms)

**Comment by mikeferguson** [comment]
fix merged
