### ISSUE TITLE
Test Broken: AttachedBodyTester

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#111]
/home/schitta/code/moveit/src/moveit_core/collision_detection_fcl/test/test_fcl_collision_detection.cpp:320: Failure
Value of: res.collision
  Actual: false
Expected: true
[  FAILED  ] FclCollisionDetectionTester.AttachedBodyTester (759 ms)

**Comment by mikeferguson** [comment]
fix merged
