### ISSUE TITLE
Test Broken: PositionConstraintsFixed

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#112]
Error:   Link '' not found in model 'pr2'
         at line 1083 in /home/schitta/code/moveit/src/moveit_core/robot_model/src/robot_model.cpp
Warning: Position constraint link model  not found in kinematic model.  Constraint invalid.
         at line 278 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: No frame specified for position constraint on link 'l_wrist_roll_link'!
         at line 284 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: No frame specified for position constraint on link 'l_wrist_roll_link'!
         at line 284 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: No frame specified for position constraint on link 'l_wrist_roll_link'!
         at line 284 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:421: Failure
Value of: pc.decide(ks).satisfied
  Actual: false
Expected: true
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:436: Failure
Value of: pc.decide(ks).satisfied
  Actual: false
Expected: true
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:448: Failure
Value of: pc.decide(ks).satisfied
  Actual: false
Expected: true
[  FAILED  ] LoadPlanningModelsPr2.PositionConstraintsFixed (617 ms)

**Comment by mikeferguson** [comment]
fix merged
