### ISSUE TITLE
Test Broken: kinematic_constraints OrientationConstraintsSimple

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#114]
Error:   Link '' not found in model 'pr2'
         at line 1083 in /home/schitta/code/moveit/src/moveit_core/robot_model/src/robot_model.cpp
Warning: Could not find link model for link name 
         at line 501 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: Orientation constraint for link 'r_wrist_roll_link' is probably incorrect: 0.000000, 0.000000, 0.000000, 0.000000. Assuming identity instead.
         at line 509 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: No frame specified for position constraint on link 'r_wrist_roll_link'!
         at line 514 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: The weight on position constraint for link 'r_wrist_roll_link' is near zero.  Setting to 1.0.
         at line 536 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: Near-zero value for absolute_x_axis_tolerance
         at line 543 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: Near-zero value for absolute_y_axis_tolerance
         at line 546 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
Warning: Near-zero value for absolute_z_axis_tolerance
         at line 549 in /home/schitta/code/moveit/src/moveit_core/kinematic_constraints/src/kinematic_constraint.cpp
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:666: Failure
Value of: oc.decide(ks).satisfied
  Actual: true
Expected: false
[  FAILED  ] LoadPlanningModelsPr2.OrientationConstraintsSimple (619 ms)

**Comment by mikeferguson** [comment]
fix merged
