### ISSUE TITLE
Test Broken: kinematic_constraints VisibilityConstraintsSimple

### ISSUE THREAD

**Issue by sachinchitta** [moveit/moveit_core#115]
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:704: Failure
Value of: vc.decide(ks, true).satisfied
  Actual: false
Expected: true
/home/schitta/code/moveit/src/moveit_core/kinematic_constraints/test/test_constraints.cpp:710: Failure
Value of: vc.decide(ks, true).satisfied
  Actual: false
Expected: true
[  FAILED  ] LoadPlanningModelsPr2.VisibilityConstraintsSimple (755 ms)

**Comment by mikeferguson** [comment]
fix merged
