### ISSUE TITLE
Feature request: Add better functionality for adding Time Parametrization to a Cartesian Trajectory

### ISSUE THREAD

**Issue by moicez** [moveit/moveit_core#141]
In the case where computeCartesianPath is used, in many cases it is necessary to add Time Parametrization to the trajectory output.

Here is an example of how to add Time Parametrization currently:
group.computeCartesianPath(waypoints,  0.01,  // eef_step, 0.0, trajectory_msg, false);
robot_trajectory::RobotTrajectory rt(group.getCurrentState()->getRobotModel(), "arm_gp");
  rt.setRobotTrajectoryMsg(*group.getCurrentState(), trajectory_msg);
  trajectory_processing::IterativeParabolicTimeParameterization iptp;
  success = iptp.computeTimeStamps(rt);
  ROS_INFO("Computed time stamp %s",success?"SUCCEDED":"FAILED");
  rt.getRobotTrajectoryMsg(trajectory_msg);
  plan.trajectory_ = trajectory_msg;

Something better could be:
group.addTimeParametrization(trajectory);

Or call time parametrization when computing the cartesian path.

**Comment by mikeferguson** [comment]
https://github.com/ros-planning/moveit/issues/160
