### ISSUE TITLE
Use of Eigen in MoveIt

### ISSUE THREAD

**Issue by adnanmunawar** [moveit/moveit_core#150]
Whenever I compile even a simple piece of code in ros I get the error 
Eigen/Geometry: No such file or directory and/or
Eigen/Core : No such file or directory. 

The simplest code that I have written thus far is 
# include <ros/ros.h>
# include <moveit/move_group_interface/move_group.h>
# include <moveit/planning_scene_interface/planning_scene_interface.h>
# include <ros/ros.h>
# include <moveit_msgs/DisplayTrajectory.h>

int main(int argc, char *\* argv)
{
    moveit::planning_interface::MoveGroup group("first_three_joints");
    moveit::planning_interface::PlanningSceneInterface planning_scene_interface;

```
ros::NodeHandle node;
ros::Publisher display_publisher = node.advertise<moveit_msgs::DisplayTrajectory>("/move_group/display_planned_path",1,true);
moveit_msgs::DisplayTrajectory display_trajectory;

ROS_INFO("Reference frame: %s", group.getPlanningFrame().c_str());
while(1);
```

}

The error is attached below:
adnan@ad:~/hydro_workspace$ catkin_make
Base path: /home/adnan/hydro_workspace
Source space: /home/adnan/hydro_workspace/src
Build space: /home/adnan/hydro_workspace/build
Devel space: /home/adnan/hydro_workspace/devel
Install space: /home/adnan/hydro_workspace/install
#### 
#### 
#### 
#### 

[100%] Building CXX object psm1_controller/CMakeFiles/psm1_controller_node.dir/src/psm1_controller.cpp.o
In file included from /opt/ros/hydro/include/moveit/robot_model/joint_model_group.h:41:0,
                 from /opt/ros/hydro/include/moveit/robot_model/robot_model.h:48,
                 from /opt/ros/hydro/include/moveit/robot_state/robot_state.h:41,
                 from /opt/ros/hydro/include/moveit/move_group_interface/move_group.h:40,
                 from /home/adnan/hydro_workspace/src/psm1_controller/src/psm1_controller.cpp:2:
/opt/ros/hydro/include/moveit/robot_model/joint_model.h:47:26: fatal error: Eigen/Geometry: No such file or directory
compilation terminated.
make[2]: **\* [psm1_controller/CMakeFiles/psm1_controller_node.dir/src/psm1_controller.cpp.o] Error 1
make[1]: **\* [psm1_controller/CMakeFiles/psm1_controller_node.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

**Comment by davetcoleman** [comment]
Perhaps try building MoveIt from source and diagnosis the problems closer to the root?
This seems like an Eigen installation problem?

**Comment by mdrx-io** [comment]
Ubuntu 14.04 installation problem. Solved for Indigo by creating a symlink from `/usr/include/eigen3/Eigen` to `/usr/local/include/Eigen`.

**Comment by alainsanguinetti** [comment]
Same problem with same fix on Ubuntu 15.04 and ROS jade

**Comment by scchow** [comment]
Same problem with same fix on Ubuntu 16.04 and ROS Kinetic encountered when following [this tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pr2_tutorials/planning/src/doc/move_group_interface_tutorial.html).

**Comment by v4hn** [comment]
@scchow I can't reproduce this over here on 16.04 / kinetic. I downloaded the referenced repositories and build them as instructed and everything builds as expected.

**Comment by davetcoleman** [comment]
we have many automated tests continuously running for around 9 versions of Ubuntu/Debian/Fedora, as specified in the [target platforms](http://www.ros.org/reps/rep-0003.html#indigo-igloo-may-2014), so the Eigen issue is likely a local misconfiguration
