### ISSUE TITLE
Why does kinematic_base have both getPositionIK and searchPositionIK

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_core#153]
Why does the plugin interface in MoveIt for inverse kinematics need both a `get` and `search` method for getting IK solutions in `kinematic_base`? Is it just some legacy function headers? It seems to me it shouldn't matter how the IK solver finds a solution under the hood. Should one of them be deprecated? 

Particularly, MoveIt never uses the `getPositionIK` function anywhere in its code base apart from its plugin header file. So it seems this function should be removed.
- In the KDL implementation, it just passes `getPositionIK` to `searchPositionIK`
- In the IKFast implementation, `searchPositionIK` passes the command on to `getPositionIK`
- In the PR2 implementation, it has two different functions, one calling an internal \* function `CartToJntSearch` and the other `CartToJnt`, so I guess the PR2 uses both but why?

**Comment by davetcoleman** [comment]
Also, while I'm at it, are there many uses cases for `getPositionFK` anymore? MoveIt performs FK internally, correct? Its pretty trivial.

**Comment by sachinchitta** [comment]
The usecase for getPositionIK is different from that for searchPositionIK. The search was intended to allow a search through the redundancy for a solution while the getPositionIK is not supposed to do that. Even though MoveIt! itself is not using the getPositionIK function call, there are other places where we are using it (with custom IK solvers). Also, there might be places in MoveIt! where getPositionIK is a better fit than the search function. 

The getPositionFK could be dropped but its part of a larger discussion that we'll need to have around the kinematics plugins.

**Comment by davetcoleman** [comment]
I understand there are analytical and numerical methods to IK, but it seems like in practice there is no difference between these two functions in this plugin. `searchPositionIK` does not allow redundant/multiple solutions to be returned, so is in practice no different that getPositionIK. Am I mistaken? 

> its part of a larger discussion that we'll need to have around the kinematics plugins.

Agreed, it's definitely a larger discussion.

**Comment by davetcoleman** [comment]
Moved to https://github.com/ros-planning/moveit_core/issues/161
