### ISSUE TITLE
PlanningScene constructor should take a RobotModelConstPtr.

### ISSUE THREAD

**Issue by hersh** [moveit/moveit_core#165]
Currently it needs a RobotModelPtr instead of a RobotModelConstPtr.  Internally it assigns it to a RobotModelConstPtr member variable anyway, so the change should not affect anything.  Anything other than allowing me to remove the ugly boost::const_pointer_castmoveit::core::RobotModel() calls in my code, that is.

I should probably fix this myself, but I don't feel like it right now.  Leaving the bug as a reminder.

**Comment by mikeferguson** [comment]
Fixed by #184
