### ISSUE TITLE
release indigo branch

### ISSUE THREAD

**Issue by tfoote** [moveit/moveit_core#176]
I've created an indigo-devel branch with the patches necessary for supporting Saucy and Trusty re: https://github.com/ros/rosdistro/issues/4633

Please release this into indigo.

**Comment by davetcoleman** [comment]
This is unfortunate because it has previously been announced there would not be an indigo branch
https://groups.google.com/forum/#!searchin/moveit-users/indigo$20branch/moveit-users/0NuSq8_TgLE/uU8k5gKCHAkJ

**Comment by tfoote** [comment]
They do not need to diverge and can remain API compatible. The users don't
need to know anything is different to use it. If you really want a single
branch you can also play games with patching the files in the gbp stage.
 However I suggest that doing the simplest thing and maintain the parallel
branches will be the least work in the long run as it will lead to the
fewest complications.  If you play games patching in the gbp tools for
building from source will not work correctly.

**Comment by tfoote** [comment]
Thinking about it another possibility is for moveit to provide it's own redirecting package which diverges and expose the same interface so moveit itself does not need to diverge. If this approach is chosen please keep it namespaced and clearly documented that this should not be a general dependency going forward but is a shim for moveit to avoid branching.

**Comment by acornacorn** [comment]
I think we want to go with the 2 branches method that it looks like Tully set up already.  Maintaining 2 branches is a pain, but hopefully we will be able to keep them pretty close together so the same changes can be applied to both branches.  We still plan to continue our main development in hydro, but these developments should also work in Indigo.

I tried building moveit for Indigo on Ubuntu 14.04 a while ago and hit a lot of dependency problems (ran out of time debugging them and gave up).  Are the Indigo moveit branches working nowadays (i.e. with this patch)?  (Maybe someday I'll get back to trying Indigo out...).

**Comment by mikeferguson** [comment]
@acornacorn The hydro-devel branch was already up to date for indigo (I've been running under indigo for some time now) and this indigo-devel branch is just forked from hydro-devel, should be fine in indigo
