### ISSUE TITLE
First steps: c++ tutorial is working, python not!

### ISSUE THREAD

**Issue by garbage98** [moveit/moveit_core#197]
Hi,

I am walking through this tutorial (http://docs.ros.org/hydro/api/pr2_moveit_tutorials/html/planning/scripts/doc/move_group_python_interface_tutorial.html). Unfortunately when using the tutorial the predefined tutorial example launch file (roslaunch pr2_moveit_tutorials move_group_python_interface_tutorial.launch) Rviz is launched correctly and the PR2 is shown. Unfortunately there is no movement or execution of the suggested behaviour.

When trying the corresponding launch file of the c++ tutorial (roslaunch pr2_moveit_tutorials move_group_interface_tutorial.launch) the robot moves correctly.

Is the python tutorial broken? Where should I look to fix this issue?

I am using Hydro and Ubuntu Precise. Python 2.7 is installed, too.

Thanks!

**Comment by mikeferguson** [comment]
hydro/precise no longer supported -- tutorials have been majorly updated in the past 2 years
