### ISSUE TITLE
Collision checking ignores some collada meshes.

### ISSUE THREAD

**Issue by hersh** [moveit/moveit_core#202]
I have worked around this for the time being by converting to .stl collision meshes, but when I use collision checking with the UR5 model from http://github.com/ros-industrial/universal_robot, it would see no problem with poking the arm through a table, as long as the elbow was sticking out far enough past the far side:

```
\ |
 \|
  |
  |\
  | O
  |/
  |
 /|
/ |
```

I think there may be a problem with scales or orientations or something, as it would sometimes detect collisions where there did not appear to be any.

**Comment by mikeferguson** [comment]
ported to new repo, see linked ticket above
