### ISSUE TITLE
Storing distance field for collision detection

### ISSUE THREAD

**Issue by mikeferguson** [moveit/moveit_core#215]
A number of planning algorithms (that are not yet or no longer in MoveIt) require a distance field. In the old SBPL interface, this was handled by having a different collision checker, which SBPL was hardcoded to use (or fallback and not use the distance field but have terrible performance). I'd like to avoid this in the future, which means having a standard storage spot for a distance field. So, where should we store this? I see three possible places:
- planning_scene::PlanningScene - We could hold a boost::shared_ptr to a distance_field in planning scene, making it always available to a number of things. The downside is that the planning_scene is already pretty cluttered with a lot of stuff.
- collision_detection::World -- collision geometry is stored here for collisions, which also includes the octomap. This class also already has all the callbacks coming in for change in objects. However, the distance_field is an alternate representation of the geometry that is already stored in World, so maybe this is not the best place to put it, but this location is what I'm leaning towards.
- collision_detection::CollisionWorld -- we could also store here, since the distance_field is an alternate representation of the data in World.

With any of these approaches, when the distance field isn't used, the pointer could be NULL (as is the case with the WorldDiff in PlanningScene) avoiding the cost of updating. With the new collision_plugin structure, we can easily setup the distance_field to be non-null when the collision checker wants a distance field.

A final possibility which avoids changing any of the above classes, is to create a new collision_detection::CollisionWorldWithDistanceField class that is derived from CollisionWorld and from which all distance-field based collision detectors are derived from, and then planning algorithms can try a dynamic_cast to this class and retrieve the field. I think the runtime penalty is not too high, as the only time the cast would occur is during setup for the motion planning request.

@isucan Any thoughts on this?

**Comment by isucan** [comment]
@mikeferguson , this would be a great addition to MoveIt. I think the distance field should be in the PlanningScene. That is the object intended to contain all the necessary information for a planner to perform its computation. The DistanceField is a different concept than a collision checker, so I think it should be available directly. Of course, a collision detection wrapper could (should) be  implemented as well, for ease of use in planner. Does this make sense?

**Comment by mikeferguson** [comment]
It does make sense to make it a part of the PlanningScene. I actually have spent a bit of time today looking more into the API, and I think that means we still have two options since the PlanningScene actually stores the geometric data about objects in a collision_detection::World instance, so:
- We can add the field to collision_detection::World, which is already passed to the CollisionWorld instance (the only other thing CollisionWorld API gives us is the RobotState for a particular check). This class also already gets all the callbacks for objects being added/removed/moved. Since the PlanningScene already has the World instance, we can simply add a method to getDistanceField and return the distance field contained in the World instance.
- The alternative is to simply add a DistanceField to the PlanningScene. It would appear it has to be an observer to changes in the World, so it will still interact with that instance. Further, we'll have to add functions to pass the DistanceField pointer into the CollisionWorld instance as we do with the World instance.

After reading through more code today, I'm leaning towards the first option of putting it in collision_detection::World. Any objections? I'll try to get a draft PR together on this later this week.

**Comment by isucan** [comment]
That is a good point! World class is the right place.

**Comment by mikeferguson** [comment]
This is still in progress, but there were other things I found were needed and it will be another week or so before I actually have a PR for this issue. Current work is in https://github.com/mikeferguson/moveit_core/tree/distance_field_world

**Comment by davetcoleman** [comment]
I'm curious about this new feature - could I use my current OMPL planning methods but now use a cost function that takes into account distance to nearest obstacle? Does maintaining this data structure computationally cost much more than the current collision checking methods? Is it just extra book keeping?

**Comment by mikeferguson** [comment]
You could use the distance field inside any planner or collision checker. Maintaining the distance field will require some extra computation -- whenever the world is updated (object added, removed, etc). I haven't quite figured out the overhead is for the worst case, which is basically when the octomap updater is running, it is something I plan to check on as I implement this. Because it does require some overhead, my plan is to make this an opt-in feature (by a parameter).

**Comment by mikeferguson** [comment]
ported to moveit repo
