### ISSUE TITLE
Reusing Constraint Samplers

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_core#217]
Currently all constraint samplers are considered "disposable" in that they are created and destroyed liberaly and are not reusable for different constraints. By this I mean:
- Constraint samplers are generated new for every planning request (e.g. planning_context)
- Once you pass a `Constraints.msg` to them, you cannot change that constraint

I'm working on a humanoid constraint sampler that is slow to load because it replies on KDL for stability checking and uses threading so has to load ~24 IK solvers to allow thread safety. Clearly, reloading these samplers is not light weight. I'd also like my sampler to take in different constraints as needed (e.g. stability constraints, another feature I've created) so am thinking a change in the ConstraintSampler header might be required.

What if every time you call Sample() you could optionally pass in a different set of constraints? I'm also looking into reusing constraint samplers within the planning pipeline. Thoughts?

@isucan

**Comment by isucan** [comment]
This is an interesting idea, and I think we can do something nice to support this. My suggestion would be to define a unique ID for every set of constraints. The constraints message already has this ID, but we should probably generate a serialization from the Constraints message. If you look in the constraints library, this is already done: hex strings corresponding to the constraints message are used as key to identify samplers. We could modify the constraint sampler allocator to cache these samplers by key. This should fit pretty well with the existing setup. Does this make sense?

**Comment by davetcoleman** [comment]
I'm not sure what you are referring to by _constraints library_ - the `constriant_samplers`, `kinematic_constraints`, or `constraint_sampler_manager_loader`? i.e. where can I find this hex string code?

**Comment by isucan** [comment]
this is in the ompl planning package, in the constraint_library object

**Comment by davetcoleman** [comment]
[Found it](https://github.com/davetcoleman/moveit_planners/blob/indigo-devel/ompl/ompl_interface/src/constraints_library.cpp) thanks!

What about my idea of having the ability to pass in constraints within the `sample()` command? I'm already playing around with this change but am sure there are larger issues to be dealt with.

**Comment by mikeferguson** [comment]
@davetcoleman -- closing this, please port to moveit repo if this is still an issue you're interested in
