### ISSUE TITLE
Request for feature: MoveIt informing what links are causing red collisions and why

### ISSUE THREAD

**Issue by UltronDestroyer** [moveit/moveit_core#222]
This would be super helpful for debugging why things are going red and wonky :-)

**Comment by isucan** [comment]
I think this is available in the last tab of the rviz plug-in. The names of
the colliding links should show up there.

**Comment by UltronDestroyer** [comment]
You're right. It also helped debug my problem. A supposed working link was spawning inside another link, causing a collision. It wasn't being disabled for some reason though. I'd like insight on that because after disabiling every collision check for every link in the robot, it was still red.
