### ISSUE TITLE
Wrong vertices order when dae contains normals

### ISSUE THREAD

**Issue by ahoarau** [moveit/moveit_core#225]
Hello,

I'm trying to read and publish the vertices point from the **collision meshes**.
It **works** great if the dae files does **NOT** contain normals (in meshlab you can export your STL files to DAE with or without normals).
A few examples :  https://github.com/ahoarau/robot_model_to_pointcloud

I'm using using simply : 
getLinkModelsWithCollisionGeometry -> getShape -> vertices (3k), vertices (3k+1), vertices (3k+2)
 and getGlobalCollisionBodyTransform

But if the dae files contains normals, like the baxter, it seems to be **rotated by pi/2 around x** : 
![baxter_w](http://googledrive.com/host/0B6zWJ1Gzg1UTUW1rYVpiMUZvUkk/baxter_w_normals_small.png)

If I export the dae (let's say the base) **without the "normals" option**, it **works** : 
![baxter_wo](http://googledrive.com/host/0B6zWJ1Gzg1UTUW1rYVpiMUZvUkk/baxter_wo_normals_small.png)

Note : I'm using Ubuntu 12.04 + ROS Groovy

**Comment by mikeferguson** [comment]
Groovy is no longer supported, no action on this ticket in over a year, closing ticket as we are porting this repo -- if this is still an issue, please open a new ticket against https://github.com/ros-planning/moveit
