### ISSUE TITLE
Capability to remove waypoints from robot_trajectory

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_core#229]
I'm guessing it's a concious design decision, but I just discovered that there are various ways of adding waypoint to trajectories, but apparently (?) no way to remove them (looking at https://github.com/ros-planning/moveit_core/blob/indigo-devel/robot_trajectory/include/moveit/robot_trajectory/robot_trajectory.h).

What I want to do is essentially removing the first x waypoints in a trajectory. The way I'd do it right now is creating a new trajectory and iterating over the indices I want to have in my reduced trajectory and inserting them into the new one. Would it be reasonable to add a method for removing waypoints, or is the method I outlined the recommended one?

**Comment by davetcoleman** [comment]
+1 I think that would be a nice feature to add, I don't see how it could hurt anything
