### ISSUE TITLE
Possible bug in transformVector3

### ISSUE THREAD

**Issue by dornhege** [moveit/moveit_core#235]
Hi,
I just stumbled upon this, so if this is actually correct please disregard it.

```
void transformVector3(const std::string &from_frame, const Eigen::Vector3d &v_in, Eigen::Vector3d &v_out) const
{
    v_out = getTransform(from_frame).rotation() * v_in;
}
```

The code only takes the rotation part. I believe it should use the complete transform to transform a Vector3.

**Comment by sachinchitta** [comment]
transformVector3 seems to assume that v_in and v_out are "free" vectors, not points. This should be in the documentation though - it looks like its not used anywhere else within moveit_core or moveit_ros.

**Comment by dornhege** [comment]
OK, makes sense. In that case I'd just leave this open as a "documentation bug".

**Comment by davetcoleman** [comment]
Why not just improve the documentation? https://github.com/ros-planning/moveit_core/pull/236
