### ISSUE TITLE
capsule support in moveit_core

### ISSUE THREAD

**Issue by arocchi** [moveit/moveit_core#239]
Hello everyone,
does moveit support as of now capsule geometries when checking collisions?
The capsule geometry distance computation has been implemented last year in fcl (see https://github.com/flexible-collision-library/fcl/pull/37) and it would be nice to access this feature directly through MoveIT (see https://github.com/Karsten1987/sot_fcl_distance_computation/blob/master/src/DistanceComputation.cpp where a cylinder geometry is treated as a capsule)

**Comment by mikeferguson** [comment]
AFAIK, all of the moveit collision checking is limited to types that can be represented by a shape_msgs message -- of which I believe there is no capsule.

**Comment by arocchi** [comment]
Yes you're right https://github.com/ros/common_msgs/blob/jade-devel/shape_msgs/msg/SolidPrimitive.msg it's a problem of the whole stack... that should e addressed starting from the ros/common_msgs repo :\

**Comment by davetcoleman** [comment]
Doesn't seem like it would be hard to add a capsule solid primitive

**Comment by arocchi** [comment]
@davetcoleman does it mean you are willing to take a stab at it? :)

**Comment by davetcoleman** [comment]
Sorry, I have no need for capsule geometries at the moment

**Comment by arocchi** [comment]
@davetcoleman if I have time in the future I might take a look at it. Anyway, when I was talking about the whole stack, I intended things like urdfdom :\

**Comment by mikeferguson** [comment]
ported to moveit repo, see linked issue above
