### ISSUE TITLE
class fcl::CollisionObject’ has no member named collisionGeometry

### ISSUE THREAD

**Issue by StanleyYake** [moveit/moveit_core#240]
Hi there:
    Because I followed the "Ros by example volume 2" writed by R.Patrick Goebel, he suggest to build it from source.But I encountered with this after catkin_make in my catkin_ws/src directory: class fcl::CollisionObject’ has no member named ‘collisionGeometry'
![screenshot from 2015-05-07 17 14 31](https://cloud.githubusercontent.com/assets/7522853/7512221/0b66ccee-f4de-11e4-8915-72128ce435df.png)

**Comment by mikeferguson** [comment]
If there is going to be any chance of getting help on this, this ticket is going to need a lot more information -- what ROS distro are you using? what OS version? what branch/tag have you checked out for each repo that you are building from source? what version of FCL are you using, and is it from debians or source?

**Comment by StanleyYake** [comment]
Hi mikeferguson:
I 'm using the ROS Hydro on Ubuntu 12.04, and used the default repo when building from source, thx for you reminds, the mistake is that the default repo is indigo, after changing to Hydro, I have build it successfully, thx again :+1:
