### ISSUE TITLE
Collision checking for attached objects

### ISSUE THREAD

**Issue by avoelz** [moveit/moveit_core#241]
Hello,

I have a robot trajectory of which I know that it is collision-free. Now I want to check whether it is still collision-free in combination with an attached object. Currently I see the following options:
1) perform full collision checking
2) perform collision checking limited to the joint model group that includes the link with the attached object
I could not find a method for restricting collision checking to a specific link or attached body. One workaround would be to modify the allowed collision matrix, so that all collision checks not including the attached body are skipped. Another workaround would be to define a group that contains only the link with the attached body and limit collision checking to that group. I like none of these workarounds because they require changing something I don't want to change (ACM respectively SRDF).

Is there any option I did not see?

If not, then I propose to include something like a link_name or attached_body_name in the collision_detection::CollisionRequest structure and use a method similar to CollisionData::enableGroup to restrict the active components to the desired link or attached body. Any thoughts on this?

@isucan @davetcoleman Any thoughts on this?

**Comment by mikeferguson** [comment]
This is more of a question than an actionable issue -- modifying the ACM is probably the way to go right now.

Closing as we are porting this repo -- if this is still an issue, please open a new ticket against https://github.com/ros-planning/moveit
