### ISSUE TITLE
Dynamically Reconfigure Robot/Scene

### ISSUE THREAD

**Issue by ndantam** [moveit/moveit_core#249]
It would be useful to able to dynamically change the kinematics of the
robot.  For example, picking a tray containing several objects should
incorporate the child objects of the tray into the robot.  This is
roughly possible by attaching as collision objects all children of the
picked object; however, this is an additional step for something which
could be managed based on the kinematic tree of the robot and scene.

It seems that this may be difficult to implement since moveit
separates the RobotModel and the PlanningScene.  Are the underlying
data structures similar?  Does the PlanningScene consider
relative transforms or are all object poses in the global frame?

I think the simplest implementation would be to treat both robot and scene as
kinematic trees using the same data structure.

EDIT: AFAICT, scene geometry is contained in collision_detection::World::Object instances  (https://github.com/ros-planning/moveit_core/blob/0.6.15/collision_detection/include/moveit/collision_detection/world.h#L72)  and robot geometry is contained in moveit::core::LinkModel  instances (https://github.com/ros-planning/moveit_core/blob/0.6.15/robot_model/include/moveit/robot_model/link_model.h#L70).  This dichotomy seems unnecessary.  Is there an advantage that I'm overlooking?

**Comment by dornhege** [comment]
MoveIt does not have a kinematic tree of the scene. All objects are considered to be in the planning frame (unless attached). I'm not sure, if the added complexity of attached fixed kinematic chains instead of objects warrants this feature. These will not be treated any different during planning to all objects being directly attached.

**Comment by mikeferguson** [comment]
This is a fairly extensive feature request that has seen no movement in a while, closing as we are porting this repo -- if this is still an issue, please open a new ticket against https://github.com/ros-planning/moveit
