### ISSUE TITLE
Magic code in RobotState

### ISSUE THREAD

**Issue by simonschmeisser** [moveit/moveit_core#277]
There is quite some alignment related code in RobotState that is hard to read and uses stuff like malloc etc.

I think this should be changed for properly aligned std::vectors. See 
[Using STL Containers with Eigen](http://eigen.tuxfamily.org/dox/group__TopicStlContainers.html) for details on how to implement this.

**Comment by mikeferguson** [comment]
I believe this was intentionally done as a major performance boost: https://groups.google.com/forum/#!msg/moveit-users/ptnMoi13sXI/XIuPMz5BBHIJ

**Comment by simonschmeisser** [comment]
I'm just proposing to replace the manually allocated chunk of memory with a vector, not to "revert" back to having a complete and complicated data structure. But I guess a PR would be more helpful than words ... let's keep this closed

**Comment by v4hn** [comment]
+5 feel free to reopen the issue against the new repo please.
I had to hunt down a bug involving this code last week and it's quite horrible.
If you could link to some resources that explain how to allocate the memory properly,
that would be great.
C++11 is allowed as we will clearly not touch this in indigo or jade anymore.
