### ISSUE TITLE
Potential for change in fcl package name

### ISSUE THREAD

**Issue by scpeters** [moveit/moveit_core#280]
There is some discussion about using the upstream version of the fcl package in ROS K instead of the ROS version (see https://github.com/ros-gbp/fcl-release/issues/1 ). If we change this, then a `kinetic-devel` branch will need to be created so the `package.xml` can be modified with the new name.

**Comment by davetcoleman** [comment]
I'm happy to create those branches, sounds like a good idea

**Comment by scpeters** [comment]
Thanks!

**Comment by scpeters** [comment]
The fcl rosdistro pull request has been merged. I can make a pull request here as soon as the `kinetic-devel` branch is created.

**Comment by davetcoleman** [comment]
There is now a kinetic-devel branch!

**Comment by scpeters** [comment]
Thanks for making the branch, see #286 for the new rosdep name.
