### ISSUE TITLE
add handles to planning_interface base class

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_core#34]

**Comment by mikeferguson** [comment]
@isucan, could you elaborate on this ticket?

**Comment by isucan** [comment]
I believe this is now implemented. Originally the planning interface had a solve function itself. I did not like that because you could not easily use multiple planners from the same library at the same time. Currently, the planning interface allows us to create a context (which initially i thought I was going to call a handle) and the context has a solve function.
