### ISSUE TITLE
IK perf for unreachable poses

### ISSUE THREAD

**Issue by acornacorn** [moveit/moveit_core#40]
The IK seems quite fast but slows down a lot when requested to calculate an unreachable pose.

Idea: a certain set of poses could be precalculated as impossible.  For example for a chain with only revolute joints any end position farther than the sum of the link lengths is impossible.  Would it make sense to store such info (e.g. a sphere radius per joint group) so that some requests can be trivially rejected?  Such calculations could be done per group by the SetupAssistant and stored in the srdf.

**Comment by sachinchitta** [comment]
There's a kinematics_cache package in moveit_core that does some of this. It needs a little bit of reworking that we could talk about.

**Comment by isucan** [comment]
I think the optimization acorn mentions is different than the cache. We should have it in, separate from that cache

**Comment by mikeferguson** [comment]
ported to new repo
