### ISSUE TITLE
rework CollisionRequest API

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_core#44]
Ideally split into CollisionRequest and DistanceRequest.

For distance, also return closest points pair;
in the distance request, perhaps a max distance of interest would be useful.

attn @acornacorn

**Comment by poftwaresatent** [comment]
Another thing to consider concerns how to handle collisions in the distance request. The simplest way of course is to say "there is a collision so we do not have distance info." OTOH if we want to use the distance request in order to move a colliding link such that it becomes free, something fancier (e.g. minimum separation distance) would be required.

**Comment by acornacorn** [comment]
I was thinking we could simplify the collision detection interface quite a bit by reducing the number of functions and placing the extra parameters in the CollisionRequest.  The Collision request could include 
- whether we want self collisions, intra-group collisions, and/or world collisions (all by default)
- the ACM if there is one.
- whether we want colliding bodies and/or contact points (this is already in there)
- whether we need distance information, and whether we want distance information for interpenetrating bodies
- whether we need the closest points pair
- etc

This would replace 14 functions (variants of checkCollision, checkRobotCollision, checkWorldCollision, distanceRobot, and distanceWorld) with just 2 variants:

<pre>
   void checkCollision(const CollisionRequest &req,
                       CollisionResult &res,
                       const CollisionRobot &robot,
                       const robot_state::RobotState &state) const;
   void checkCollision(const CollisionRequest &req,
                       CollisionResult &res,
                       const CollisionRobot &robot,
                       const robot_state::RobotState &state1,
                       const robot_state::RobotState &state2) const;
</pre>

This would also allow us to add features in the future without changing the interface (by adding fields to CollisionRequest and CollisionResult).

There is more opportunity to optimize if the distance request and collision request come together when the client needs both.  We also benefit by only doing calculations the client actually needs us to do.

If necessary we can leave all the existing functions (which can be implemented by calling into the above 2) and perhaps mark them deprecated.

-Acorn

**Comment by isucan** [comment]
This has been revisited. The split in requests was not done due to efficiency concerns.
