### ISSUE TITLE
use ids in AllowedCollisionMatrix as message

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_core#50]

**Comment by isucan** [comment]
@acornacorn since we talked about this yesterday; turns out there is also a ticket :)

**Comment by mikeferguson** [comment]
@isucan could you elaborate on this? What did you intend to do and why?

**Comment by isucan** [comment]
Currently the ignored collision matrix is quite inefficient. If we had a mapping from object names to integers then we could avoid doing map lookups but instead to lookups by index in a vector/matrix.

**Comment by mikeferguson** [comment]
Ok, so that means what I thought it meant -- I wasn't sure if I was missing something because I didn't know what you meant by "as message"
