### ISSUE TITLE
Unwanted transform in setIK function of joint_state_group

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_core#56]
Hi everyone, I'm encountering a little issue with the setIK() function provided by joint_state_group.
I have a ikfast based plugin implementing the kinematics_base interface. The base_frame for the plugin is the "/utorso" frame. I also have goal pose represented by a geometry_msgs/Pose already given in the "/utorso" frame. If I call setIK() on my joint group with this goal pose, I would expect that the the pose is forwarded to getPositionIk unmodified. Instead, the solver's base_frame is compared against the joint group parent's model frame. and a transformation is applied to the pose (see https://github.com/ros-planning/moveit_core/blob/groovy-devel/robot_state/src/joint_state_group.cpp#L354).
This results in a wrong pose being used to query IK in my case. Why aren't the solver base_frame and the goal pose frame_id compared against each other?
If I transform my pose to the "/pelvis" frame before and use this transformed pose as the goal for setIK(), the IK query seems to work correctly (but uses a tf query that should not be needed really).
Also, my ikfast based plugins seem to work fine for interactive marker based control with the demo.launch that gets generated by the setup assistant, suggesting that their frame setup is correct.

**Comment by isucan** [comment]
Is the issue that the computed result is incorrect? What I would expect to happen is that you have 2 transforms that cancel each other (up to numerical precision) applied to your pose. If running demo.launch gives expected results, then things should be fine. However, as you point out an optimization is in order. Is that what you would like? Adding this optimization should not be a problem, but I'd like to make sure there are no other frame transform issues.

**Comment by skohlbr** [comment]
Yes, the computed result is incorrect. For generating the goal, I sample valid fk, make sure call ik for the resulting pose and send the goal pose to planning (with "utorso" frame_id). I added debug ouput in the IK's solve() step, so I can see with which exact pose IK was called.

When generating this is what I get from IK:

<pre>
[ INFO] [1365419276.366940662, 23.129000000]: tx: -0.530366 ty: -0.463973 tz: 0.386625
[ INFO] [1365419276.367035419, 23.129000000]: rotmatrix:
-0.026622  -0.30683 -0.951392
 0.118358  0.944067 -0.307779
 0.992614 -0.120798 0.0111827
</pre>

Sending off the pose to my planning node and calling setIK, the following is in the end passed into the IK's solve() step:

<pre>
[ INFO] [1365419276.371567235, 23.129000000]: tx: -0.517866 ty: -0.463973 tz: 0.246625
[ INFO] [1365419276.371703604, 23.129000000]: rotmatrix:
-0.026622  -0.30683 -0.951392
 0.118358  0.944067 -0.307779
 0.992614 -0.120798 0.0111827
</pre>

This is due to the fact that, while both the solver's base frame (ik_frame) and the goal pose frame_id are "utorso", the ik_frame is compared to the parent of the joint group (in my case "world") and then the pose is transformed. This is also demonstrated by some debug output I put into the setIK function:

<pre>
ik_frame: utorso joint_model_group_parent_model:  world
tip_frame: r_hand tip:  r_hand
</pre>

Like I wrote before, first transforming the pose into the "pelvis" frame and then passing it to setIK() seems gives results looking correct, but even then there is a slight difference between the poses passed to the IK solve() function, so some kind of transform is still happening.

**Comment by skohlbr** [comment]
On closer look, it seems the setIK() function taking a geometry_msgs::Pose as a input does not look at the header's frame_id in any way (/edit: See  Post below, there isn't any frame_id, we're not looking at a PoseStamped) and just converts the pose to a Eigen pose. This of course means that providing a pose using any other frame than the intended one will cause wrong behavior.

**Comment by skohlbr** [comment]
..and looking once more in the doxygen docs it says:

<pre>
The pose is assumed to be in the reference frame of the kinematic model
</pre>

So the issue is pretty much my fault because I didn't read the docs thoroughly enough :)

/edit: And stupid me missed that I'm the one stripping the pose of the frame_id already, as we only supply a non-stamped pose to setIK(). Sorry for the noise.

**Comment by isucan** [comment]
So... I am guessing problem solved? The catch is that the robot state is not necessarily aware of TF and so does not take frame ids as input

**Comment by skohlbr** [comment]
Yes, can be closed. Also makes sense not to be tf-aware in robot state. Thanks for the fast reply.
