### ISSUE TITLE
Ensure consistent convention for contact normals

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_core#61]
I'm ticketing this to ensure it has been addressed before alpha release.
Previously, FCL was reporting normals that pointed from contact1 -> contact2 for certain types (primitives, I think), and from contact2 -> contact1 for Octomap.

We need to make sure there is a standard (for all collision detectors used through the MoveIt API) for which direction a reported normal points.

**Comment by mikeferguson** [comment]
ported to new moveit repo
