### ISSUE TITLE
transforms in moveit

### ISSUE THREAD

**Issue by isucan** [moveit/moveit_core#64]
transforms need to be separated out from robot_state
Transforms needs to probably exist as a base class that offers the current functionality;
Other classes inherit from Transforms and use the frames implicitly defined by a planning scene and a robot state. only base pointers to Transforms get passed around, but the planning scene instantiates the most derived class.

**Comment by davetcoleman** [comment]
should we think about better integration with tf2?

@tfoote

**Comment by isucan** [comment]
i'd like to use tf2, but this is a separate issue.
switching to tf2 should be easy, since most of moveit does not use tf directly for transforms

**Comment by isucan** [comment]
done
