### ISSUE TITLE
updating ros-groovy-moveit* does not pull new versions of ros-groovy-geometric-shapes

### ISSUE THREAD

**Issue by egiljones** [moveit/moveit_core#66]
Pointed at the main ros repos I just ran the command 'sudo apt-get update ros-groovy-moveit*' and pulled the following packages:

Setting up ros-groovy-moveit-msgs (0.4.0-0precise-20130523-1152-+0000) ...
Setting up ros-groovy-moveit-core (0.4.0-0precise-20130523-1156-+0000) ...
Setting up ros-groovy-moveit-ros-perception (0.4.0-1precise-20130523-1223-+0000) ...
Setting up ros-groovy-moveit-ros-planning (0.4.0-1precise-20130523-1233-+0000) ...
Setting up ros-groovy-moveit-ros-move-group (0.4.0-1precise-20130523-1247-+0000) ...
Setting up ros-groovy-moveit-ros-manipulation (0.4.0-1precise-20130523-1258-+0000) ...
Setting up ros-groovy-moveit-ros-warehouse (0.4.0-1precise-20130523-1249-+0000) ...
Setting up ros-groovy-moveit-ros-planning-interface (0.4.0-1precise-20130523-1305-+0000) ...
Setting up ros-groovy-moveit-commander (0.4.0-0precise-20130523-1313-+0000) ...
Setting up ros-groovy-moveit-planners-ompl (0.3.11-0precise-20130523-1247-+0000) ...
Setting up ros-groovy-moveit-planners (0.3.11-0precise-20130523-1256-+0000) ...
Setting up ros-groovy-moveit-ros-benchmarks (0.4.0-1precise-20130523-1258-+0000) ...
Setting up ros-groovy-moveit-ros-robot-interaction (0.4.0-1precise-20130523-1249-+0000) ...
Setting up ros-groovy-moveit-ros-visualization (0.4.0-1precise-20130523-1312-+0000) ...
Setting up ros-groovy-moveit-ros-benchmarks-gui (0.4.0-1precise-20130523-1321-+0000) ...
Setting up ros-groovy-moveit-ros (0.4.0-1precise-20130523-1325-+0000) ...
Setting up ros-groovy-moveit-setup-assistant (0.3.9-0precise-20130523-1320-+0000) ...
Setting up ros-groovy-moveit-full (0.4.0-0precise-20130523-1327-+0000) ...
Setting up ros-groovy-moveit-pr2 (0.4.0-0precise-20130523-1317-+0000) ...
Setting up ros-groovy-moveit-full-pr2 (0.4.0-0precise-20130523-1329-+0000) ...
Setting up ros-groovy-moveit-ompl-planners-core (0.3.11-0precise-20130523-1256-+0000) ...
Setting up ros-groovy-moveit-ompl-planners-ros-plugin (0.3.11-0precise-20130523-1255-+0000) ...
Setting up ros-groovy-moveit-resources (0.3.1-0precise-20130520-2230-+0000) ...

I then independently needed to run 'sudo apt-get update ros-groovy-geometric-shapes' to get geometric_shapes - 
Setting up ros-groovy-geometric-shapes (0.3.4-0precise-20130523-1122-+0000) ...

This is definitely an ongoing problem - I spent a while earlier this week debugging linking errors due to having an out-of-date geometric_shapes.  I suspect dependencies withing the debs are not being set correctly.

**Comment by isucan** [comment]
The issue is that you asked for the update of the moveit packages, and you still had a version of geometric_shapes installed; The moveit packages do not specify a minimum version for the dependency, which causes the problem.
I don't think we have support for declaring minimum versions in the build/release system;
@tfoote Is this true?

**Comment by tfoote** [comment]
We have support see REP 127 http://ros.org/reps/rep-0127.html#build-depend-multiple
