### ISSUE TITLE
Support multiple collision geometries for URDF models (e.g. Atlas model) in MoveIt!

### ISSUE THREAD

**Issue by skohlbr** [moveit/moveit_core#69]
This is related to robot_model ticket 18 which can serve as an overview on the issue:
https://github.com/ros/robot_model/issues/18

It would be great to have compatibility for this in MoveIt! so we don't have to work on giving Atlas a single collision geom per link again.

**Comment by isucan** [comment]
added in Hydro as a feature. Still some issues, but fixing those separately.
