### ISSUE TITLE
Adding closest feasible state

### ISSUE THREAD

**Issue by vrabaud** [moveit/moveit_core#75]
Here is the scenario: when using an interactive marker on a less than 6 dof arm, I'd like the closest valid state to be displayed. Right now, the IR is useless on a less than 6 dof as every state is invalid. I understand adding more joint (like the torso) would solve that problem.

I'm just wondering whether that feature is possible/useful, maybe through KDL. Your call.

**Comment by isucan** [comment]
fixed
