### ISSUE TITLE
Hard coded database path

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_core#77]
There is a `WARN` from `rosconsole_bridge` being generated when launch demo.launch that says:

```
 WARN ros.rosconsole_bridge.console_bridge: Manifest not found in folder '/home/isucan/constraints_approximation_database'. Not loading constraint approximations.
```

I did a grep through all of MoveIt! as well as my robot's repos and I found two location's with **isucan** hard-coded in. After removing them, this error still did not go away (the locations didn't seem like they would effect the output, and they didn't). But I'm not sure where the output is coming from. 

The whole launch file output:
https://gist.github.com/davetcoleman/5905731

**Comment by isucan** [comment]
fixed
