### ISSUE TITLE
Installation Failure on openSUSE 12.3

### ISSUE THREAD

**Issue by teddybouch** [moveit/moveit_core#80]
I'm trying to follow the instructions on http://moveit.ros.org/wiki/Installation to install MoveIt on a laptop running openSUSE 12.3. Because rosdep does not work on my system and there isn't a fix for it yet, I've been handling dependencies manually. Generally that hsa worked well, but I have hit a hard stop with the Flexible Collision Library (FCL). It seems that the latest edition of the library is no longer a ROS package but a standalone library, and I have it installed as such. However, when I run the catkin_make in my moveit directory according to those instructions, I get the following error when it tried to make moveit_core:

CMake Error at /opt/ros/groovy/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a package configuration file provided by "fcl" with any of
  the following names:

```
fclConfig.cmake
fcl-config.cmake
```

  Add the installation prefix of "fcl" to CMAKE_PREFIX_PATH or set "fcl_DIR"
  to a directory containing one of the above files.  If "fcl" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  moveit_core/CMakeLists.txt:10 (find_package)

That it is looking for package configuration files suggests to me that Moveit may still be configured to treat it as a package, and I don't know how to re-configure it to look for the shared object library instead. Is this indeed the issue that I think it is, and is there a fix? Thanks very much.

**Comment by isucan** [comment]
Hey @teddybouch, sorry for the very late reply. Indeed FCL is a so-called 'third-party lib'. The idea is that it can be packaged in multiple ways and installed on different systems, not necessarily in a ROS context. We do however build debs for FCL, and although not a ros package, the lib provides a .cmake file so it can be found with find_package. So, if you install FCL in some way first, moveit should also build.

**Comment by suhshinhwang** [comment]
Hi,
I am also having the same problem. I'm on ROS Groovy and am trying to compile MoveIt (Groovy-Devel) from scratch. I removed OctoMap and FCL that came with ROS-Groovy to do some testing. When I run catkin_make in the MoveIt folder, the octomap dependencies work okay, but not the FCL. I run into the same problem as teddybouch
