### ISSUE TITLE
return points and normal of closest distance from collision detection

### ISSUE THREAD

**Issue by quan1992** [moveit/moveit_core#84]
As far as I know, I can get the distance between world object and any part of pr2 link through moveit API of collision detection. And I am really interested in the coordinates of pair of points that makes that shortest distance happen. However, it seems moveit API is not able to return that information. Is it possible to do that?

**Comment by hersh** [comment]
This is related to #99 which also wants to get more information back from the collision detection.  This feature would give a superset of the info requested in #99 (normal vector).
