### ISSUE TITLE
Having trouble building against ros-groovy with catkin

### ISSUE THREAD

**Issue by ibrahima** [moveit/moveit_core#9]
Hi, I'm trying to build the latest moveit stack from source and have been having some difficulty. Basically I can build moveit_core fine, and then when I try to build moveit_ompl_planners_core it fails because it can't find the headers that should be exported by moveit_core. I feel like I have a decent understand of how catkin is set up but it seems like something is missing from the CMakeLists.txt to export the include dirs for other packages to use, as described in http://www.ros.org/wiki/catkin/CMakeLists.txt#catkin_package.28.29

But I'm not sure if that's relevant here since there are many packages

Should I be trying to build using rosmake/rosbuild instead? I tried that too and that didn't work because some of the packages didn't have Makefiles so I figured I should learn the catkin system but I'm not sure what the right way is.

I have tried adding
`INCLUDE_DIRS
 66    kinematics_base/include
 67    kinematic_model/include
 68    kinematic_state/include
 69    collision_detection/include
 70    collision_detection_fcl/include
 71    kinematic_constraints/include
 72    planning_scene/include
 73    constraint_samplers/include
 74    planning_interface/include
 75    planning_request_adapter/include
 76    trajectory_processing/include
 77    distance_field/include
 78    collision_distance_field/include
 79    kinematics_metrics/include
 80    dynamics_solver/include
 81)`

To the catkin_package call in CMakeLists.txt but then it seems like those includes that depend on srdfdom/includes cause errors when compiling moveit_ompl_planners_core.

Sorry if this is a lot of noise, if I'm completely off base with what I'm doing right now I guess the most helpful thing for me would be to know how those who are actively developing moveit are compiling it. I am trying to write a planner interface for moveit for some work we are doing at Berkeley and it seemed like I should be able to compile moveit first but maybe that's not necessary either.

**Comment by ibrahima** [comment]
I've been able to build just the planner interface for OMPL in a local workspace against the deb packaged moveit libraries which is good enough for me for now, sorry for the extra noise. I guess the "Installing from source" instructions could use some updating but that's not terribly important right now.

**Comment by isucan** [comment]
Hey, you are correct in that some stuff is missing from includes. I am using a non-default setup that used to cause some problems in install space. I will try again and see if i can fix this.

**Comment by ibrahima** [comment]
Awesome, good to hear.

**Comment by ibrahima** [comment]
I'd just like to report that as of now I can build basically everything in moveit! Thanks!

**Comment by isucan** [comment]
Thanks for confirming. As soon as the latest rviz build completes, you should be able to compile the rest of things. In any case, that is a different bug than this one, so I will close it.
