### ISSUE TITLE
Help with compiling on Travis

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_core#90]
I've started using Travis with my Baxter code and I'd like to have it able to compile MoveIt from source. I've tried may times but internal compiler errors always occur - from my research it seems gcc is perhaps running out of memory on the free Travis boxes. But I'm not sure. Any advice is welcome:

https://travis-ci.org/davetcoleman/moveit_core/builds/12080425

@jbohren you are the expert who got me into this, any tips? :)

**Comment by hersh** [comment]
If it's running out of memory, you should limit it to compiling only one file at a time instead of the default parallel jobs that catkin_make uses.  Instead of `catkin_make`, try `catkin_make -j1` to limit it to a single process.

**Comment by davetcoleman** [comment]
Ah I forgot this ticket was still open - I've resolved it by using `-j2`. By default the virtual boxes appear to catkin to have 32 cores available when it doesn't actually, so you have to specify a `-j` value. But `-j1` is too slow for the 50 minute compile time limit.
