### ISSUE TITLE
workspace parameter does not influences planning for rotational joints

### ISSUE THREAD

**Issue by k-okada** [moveit/moveit_core#93]
Currently the workspace parameter only influences planning for planar & floating joints. So, the workspace definition does not affect the position of links that are moved by other types of joints (like in the case you display). Unfortunately, this is a missing feature.

https://groups.google.com/forum/?hl=ja#!topic/moveit-users/_11FJ4hVEJg

**Comment by davetcoleman** [comment]
To implement this, would we need to add another constraint sampler that always checked that all collision bodies are inside the bounding box of the workspace? Should the workspace bounding box just be implemented as collision bodies for the collision checker to handle?

**Comment by isucan** [comment]
This would have to be checked for every test for validity of a state, so efficiency is very important. The way I would do this is to check that the links we are moving have the origin of their reference frame within the defined workspace (always as a box), so this will be just a for loop and comparisons. There should be a flag for undefined workspace though. Right now we just have a planning request adapter that makes up a bounding box. We need to maybe get rid of that adapter and have the planner decide what the workspace is, and do things differently if no workspace is specified (all 0s)

**Comment by davetcoleman** [comment]
>   check that the links we are moving have the origin of their reference frame within the defined workspace

does this mean a planner could plan a motion that has part of a link go outside of the workspace, so long as its origin does not? that seems like maybe undesired behavior. i was hoping to use this workspace parameter as a way to keep my robot from hitting walls around it. is that not a good use of this functionality?

**Comment by isucan** [comment]
you are correct. In that case, I would use a slightly smaller bounding box. We can also implement the workspace as walls that get added to FCL, which would give the functionality you mention, but will potentially be slightly slower.

**Comment by davetcoleman** [comment]
Interesting trade off. I think we need to pick a definition of the workspace... if its a "planning workspace" I think not implementing it in the collision checking components might be correct, but if its a "execution workspace" or something, then we need it to always respect those boundaries in all cases. Does that sound right?

**Comment by e1000i** [comment]
So, how is finally used, and on what have incidence the definition of a workspace? It only restricts the movement search space for planar and flotating joints? Using prismatic or any other joint type while defining a workspace has not direct effect in the planing and the execution. Is that right? That should not be stated explicitly somewhere in the documentation?

**Comment by mikeferguson** [comment]
ported to new repo
