### ISSUE TITLE
Problems getting joint_states

### ISSUE THREAD

**Issue by anefg** [moveit/moveit_core#94]
Every time I try to recover the joint states of my simulated arm using the method getVariableValues()  I always get the same joint state position: 0.0, although the joints are moved.

Thanks.

**Comment by isucan** [comment]
What object are you calling getVariableValues() on? How is that object initialized? What topic are joint states published on?

**Comment by anefg** [comment]
I'm calling getVariableValues on JointStateGroup object and yes, the joint states are being published on /join_states topic.

This is the code that I'm using:

/\* Get the configuration for the joints robotnik arm_/
  robot_state::JointStateGroup_ joint_state_group = kinematic_state->getJointStateGroup("robotnik_arm");

  /\* Get the joint states for the right arm*/
  std::vector<double> joint_values;
  joint_state_group->getVariableValues(joint_values);

Thanks

**Comment by isucan** [comment]
RobotState is a data structure for holding a robot state, not necessarily populating it. You need to use a CurrentStateMonitor class, or define a PlanningSceneMonitor, or use the move_group_interface, depending on what else you need to do.
http://moveit.ros.org/doxygen/classplanning__scene__monitor_1_1CurrentStateMonitor.html
http://moveit.ros.org/doxygen/classplanning__scene__monitor_1_1PlanningSceneMonitor.html
http://moveit.ros.org/wiki/MoveGroup_Interface_tutorial

**Comment by anefg** [comment]
I have loaded the model of the robot and populated the RobotState structure. I have created an instance of MoveGroup object to be able to move it.

The code that I'm executing is:

 /\* Load the robot model */
  robot_model_loader::RobotModelLoader robot_model_loader("robot_description");

  /\* Get a shared pointer to the model */
  robot_model::RobotModelPtr kinematic_model = robot_model_loader.getModel();

  /\* WORKING WITH THE KINEMATIC STATE _/
  /_ Create a kinematic state - this represents the configuration for the robot represented by kinematic_model */
  robot_state::RobotStatePtr kinematic_state(new robot_state::RobotState(kinematic_model));

 /\* Get the configuration for the joints robotnik arm_/
  robot_state::JointStateGroup_ joint_state_group = kinematic_state->getJointStateGroup("robotnik_arm");

  /\* Get the joint states for the right arm*/
  std::vector<double> joint_values;
  joint_state_group->getVariableValues(joint_values);

**Comment by anefg** [comment]
I know that issue #96 was duplicated, but #94 was closed and I still had the problem. That's why I decided to create a new one.

So, it's necesary to have a planing scene created to get the updated joints state from the robot model?

Thanks

**Comment by anefg** [comment]
I have created an instance of PlanningSceneMonitor, but I still got 0.0 as joints pose. Which are the steps that I should follow to recover joints poses without been subscribed to joint_state topic?

**Comment by isucan** [comment]
If you call startStateMonitor() on the PlanningSceneMonitor then you can use getCurrentState() and get the current robot state.

**Comment by anefg** [comment]
Using the PlanningSceneMonitor I recover the current robot state. However I don't understand, the reason why I'm not able to get the current joint state values using the getVariableValues(). Is using the PlanningSceneMonitor the only wayto get it?
