### ISSUE TITLE
IK parameter for weighting joints

### ISSUE THREAD

**Issue by YoheiKakiuchi** [moveit/moveit_core#97]
I need a weight parameter for each joint.
Because joint near the root link such as joints in torso moved too much, 
and that is not good for a biped humanoid robot.

Joint weights should be set at kinematics.yaml or PositionIKRequest.msg

**Comment by k-okada** [comment]
code is here, should we move this ticket to moveit_ros?

https://github.com/ros-planning/moveit_ros/blob/groovy-devel/planning/kdl_kinematics_plugin/src/chainiksolver_vel_pinv_mimic.cpp

**Comment by k-okada** [comment]
memo

maybe we can use sr-inverse, and compute weight from joint limit.

http://sourceforge.net/p/jskeus/code/HEAD/tree/trunk/irteus/irtmodel.l

**Comment by isucan** [comment]
probably this should be moved to moveit_ros, yes.

**Comment by k-okada** [comment]
move to -> https://github.com/ros-planning/moveit_ros/issues/358, 
I think we  can close this ticket.
