### ISSUE TITLE
IK including virtual joint

### ISSUE THREAD

**Issue by YoheiKakiuchi** [moveit/moveit_core#98]
Now, virtual joint can not be used in IK.
Then,  virtual linear and rotational joints automatically could be added to KDL joint group.

**Comment by acornacorn** [comment]
Virtual joint is intended to connect the robot to the world.  If the first (base) joint in your robot is a linear or rotational joint then it can be added to the URDF as a real physical joint.  Then you can use a fixed joint to connect this joint to the world.  That will allow you to add the (physica) linear or rotational joint to the group and use ith with IK.

If I misunderstood your question please reopen the bug and explain further.
